### PR TITLE
removed s from module name as per conventions

### PR DESCRIPTION
**Pull request by nuria-opusvl**

### CODE REVIEW

**Comment by elicoidal** [comment]
It seems very quick for a merge isnot it? ;)

**Comment by nuria-opusvl** [comment]
I did it again, didn't I? lol I have a lot to learn.

On 08/09/15 09:48, Eric Caudal wrote:

> It seems very quick for a merge isnot it? ;)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/OCA/l10n-united-kingdom/pull/4#issuecomment-138482421.

## 

N. Arranz-Velazquez
OpusVL Odoo Specialist Team (OOST)
Product Owner

OpusVL
Drury House
Drury Lane
Rugby
CV21 3DE

T: 01788 298 450
W: www.opusvl.com

**Comment by nuria-opusvl** [comment]
Hi Eric,

I've made a few changes and a pull request:
https://github.com/OCA/l10n-united-kingdom/pull/5

Now, how do I get 3 reviewers?

Many thanks!
Nuria

On 08/09/15 09:55, Nuria Arranz Velazquez wrote:

> I did it again, didn't I? lol I have a lot to learn.
> 
> On 08/09/15 09:48, Eric Caudal wrote:
> 
> > It seems very quick for a merge isnot it? ;)
> > 
> > —
> > Reply to this email directly or view it on GitHub 
> > https://github.com/OCA/l10n-united-kingdom/pull/4#issuecomment-138482421.
> 
> ## 
> 
> N. Arranz-Velazquez
> OpusVL Odoo Specialist Team (OOST)
> Product Owner
> 
> OpusVL
> Drury House
> Drury Lane
> Rugby
> CV21 3DE
> 
> T: 01788 298 450
> W:www.opusvl.com

## 

N. Arranz-Velazquez
OpusVL Odoo Specialist Team (OOST)
Product Owner

OpusVL
Drury House
Drury Lane
Rugby
CV21 3DE

T: 01788 298 450
W: www.opusvl.com

**Comment by elicoidal** [comment]
Several options: have somebody from your team review and agree + normally somebody from OCA should naturally check all the MR and comment/approve
@gurneyalex @pedrobaeza any suggestion/comment?

**Comment by nuria-opusvl** [comment]
Ok, thanks, I'll try someone from my team here :-)

Hey, thanks for all your support and guidance.

On 10/09/15 03:25, Eric Caudal wrote:

> Several options: have somebody from your team review and agree + 
> normally somebody from OCA should naturally check all the MR and 
> comment/approve
> @gurneyalex https://github.com/gurneyalex @pedrobaeza 
> https://github.com/pedrobaeza any suggestion/comment?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/OCA/l10n-united-kingdom/pull/4#issuecomment-139097951.

## 

N. Arranz-Velazquez
OpusVL Odoo Specialist Team (OOST)
Product Owner

OpusVL
Drury House
Drury Lane
Rugby
CV21 3DE

T: 01788 298 450
W: www.opusvl.com

**Pull request merged**
