### PR TITLE
renamed to conventions

### PR DESCRIPTION
**Pull request by nuria-opusvl**

### CODE REVIEW

**Comment by dreispt** [comment]
Thanks @nuria-opusvl 
You should at wait for peer reviews though.
In this case, I would comment that the guideline is to have no plurals in module names, so it would be best named `l10n_uk_crm_report`.

**Comment by nuria-opusvl** [comment]
I can change that, it's no problem.

How do I wait for peers reviews, please? Sorry if I sound dumb, I'm 
trying to get my head around the process and the steps.

On 04/09/15 14:39, Daniel Reis wrote:

> Thanks @nuria-opusvl https://github.com/nuria-opusvl
> You should at wait for peer reviews though.
> In this case, I would comment that the guideline is to have no plurals 
> in module names, so it would be best named |l10n_uk_crm_report|.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/OCA/l10n-united-kingdom/pull/3#issuecomment-137740439.

## 

N. Arranz-Velazquez
OpusVL Odoo Specialist Team (OOST)
Product Owner

OpusVL
Drury House
Drury Lane
Rugby
CV21 3DE

T: 01788 298 450
W: www.opusvl.com

**Comment by dreispt** [comment]
I think we are missing a guide on that... (cc @jgrandguillaume )
Anyway, in a nutshell all merges should go through a peer reviewed pull request. Before being merged it should be accepted (:+1:) by at least two reviewers.

**Comment by nuria-opusvl** [comment]
That sounds sensible.

I have done another pull request with the change in the name; and now I 
would like to have it reviewed before merging. How do I get it reviewed?

Many thanks!

On 04/09/15 16:32, Daniel Reis wrote:

> I think we are missing a guide on that... (cc @jgrandguillaume 
> https://github.com/jgrandguillaume )
> Anyway, in a nutshell all merges should go through a peer reviewed 
> pull request. Before being merged it should be accepted (:+1:) by at 
> least two reviewers.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/OCA/l10n-united-kingdom/pull/3#issuecomment-137769514.

## 

N. Arranz-Velazquez
OpusVL Odoo Specialist Team (OOST)
Product Owner

OpusVL
Drury House
Drury Lane
Rugby
CV21 3DE

T: 01788 298 450
W: www.opusvl.com

**Comment by pedrobaeza** [comment]
Here you have the guide about that: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#review

**Comment by dreispt** [comment]
> I have done another pull request with the change in the name; and now I would like to have it reviewed before merging. How do I get it reviewed?

@nuria-opusvl That's the 1M$ question :smile:  
We somehow need to incentive people to participate...

**Pull request merged**
